# Generated by Django 4.0.4 on 2022-05-05 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tarefas_datainicio_alter_tarefasstatus_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 11, 16, 964047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 5, 12, 11, 16, 965047, tzinfo=utc), null=True),
        ),
    ]
